name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: autoconf
      run: sh bootstrap
    - name: configure
      run: ./configure --enable-sfcapd --enable-nfpcapd
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
